### ISSUE TITLE
Errors in the project, Request to solve

### ISSUE THREAD

**Issue by shreyas836** [Brockkoli/FraudFence#42]
while running mainMenu, the error occurs by not giving the report.html

Traceback (most recent call last):
  File "D:\phishscan360\FraudFence-main\FraudFence-main\mainMenu.py", line 162, in <module>
    printall(url, portscan_result, ssl_result, header_result,dns_result,location_result,tracer_result,directory_result,whois_result, webrisk_result)
  File "D:\phishscan360\FraudFence-main\FraudFence-main\printalloptions.py", line 41, in printall
    template = Template(file.read())
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\phishscan360\FraudFence-main\FraudFence-main\venv\venv\Lib\site-packages\jinja2\environment.py", line 1208, in __new__
    return env.from_string(source, template_class=cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\phishscan360\FraudFence-main\FraudFence-main\venv\venv\Lib\site-packages\jinja2\environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "D:\phishscan360\FraudFence-main\FraudFence-main\venv\venv\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "D:\phishscan360\FraudFence-main\FraudFence-main\venv\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 279, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'webrisk_data'.

**Comment by Brockkoli** [comment]
Api key required for wot webrisk data

**Comment by shreyas836** [comment]
Hi Brockkoli/FraudFence

Need help in Executing the program
Can we please connect through google meet?

**Comment by Brockkoli** [comment]
Hi, as this is a project for a school assignment, it is neither appropriate nor in our interest to conduct biz dealings. Nevertheless, thank you for your interest in our program.

**Comment by shreyas836** [comment]
Hi
thank you for your response
But I'm getting errors while executing the program.
Could you please specify to me what changes I need to make other than API
in the codes?
